//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlogArticulos.AccesoADatos.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public class Articulo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Articulo()
        {
            this.Comentario = new HashSet<Comentario>();
        }
    
        public int idArticulo { get; set; }
        public string titulo { get; set; }
        public string cabecera { get; set; }
        public string cuerpo { get; set; }
        public string imagen { get; set; }
        public string activo { get; set; }
        public System.DateTime fechaPublicacion { get; set; }
        public int TipoArticulo_idTipoArt { get; set; }
        public int Usuario_idUsuario { get; set; }
    
        public virtual TipoArticulo TipoArticulo { get; set; }
        public virtual Usuario Usuario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Comentario> Comentario { get; set; }
    }
}
