//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlogArticulos.AccesoADatos.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comentario
    {
        public int idComentario { get; set; }
        public string detalle { get; set; }
        public System.DateTime fechaHora { get; set; }
        public int Usuario_idUsuario { get; set; }
        public int Articulo_idArticulo { get; set; }
    
        public virtual Articulo Articulo { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
